### ISSUE TITLE
Issue when packaging with PyInstaller – awthemes theme not loading correctly

### ISSUE THREAD

**Issue by Felix00643298** [undecV/python-awthemes#2]
**Description:**

Hello, I am facing an issue while packaging my Tkinter-based application using `PyInstaller`. The application runs fine when executed directly in the development environment, but after I package it with `PyInstaller` using the following command:

```bash
pyinstaller --onefile --windowed --collect-all "awthemes" dealer_gui.py
```

The build completes successfully without any errors, but when I double-click the generated `.exe` file, I get the following error:

```
  File "dealer_gui.py", line 33, in __init__
  File "dealer_gui.py", line 44, in setup_ui
  File "dealer_gui.py", line 53, in configure_ui_theme
  File "awthemes\__init__.py", line 42, in theme_use
    tksvg.load(self.master)
  File "tksvg\__init__.py", line 25, in load
  File "contextlib.py", line 137, in __enter__
  File "tksvg\__init__.py", line 16, in chdir
  FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'C:\\Users\\J00643~1\\AppData\\Local\\Temp\\_MEI34
```

I am using the latest version of `awthemes` (0.2.1) along with `PyInstaller`.

### What I’ve tried:
- I have verified that the `awthemes` package is installed correctly in my environment.
- I used `--collect-all` to ensure that all related files for `awthemes` are bundled into the executable.
- I tried running the executable in a terminal to check for any additional error messages.

### Environment:
- `Python`: 3.x
- `PyInstaller`: version 4.x (or latest)
- `awthemes`: version 0.2.1

### Expected behavior:
The application should load the awthemes theme properly when launched from the packaged .exe. Furthermore, I want to be able to share the generated .exe with others so that they can run the application on their own computers without requiring Python or the awthemes package to be installed on their systems.

---

Could anyone help me identify the issue or suggest a fix for loading the `awthemes` theme correctly in the packaged executable?

Thank you!

**Comment by Felix00643298** [comment]
I tried an another build command：
```
pyinstaller --onefile --windowed --collect-all "awthemes" --debug all dealer_gui.py
```
and it can work on `awdark`.

However, when I  change the theme into `awbreezedark`, `.exe`file showed the following error message:
```
Traceback (most recent call last):
  File "dealer_gui.py", line 275, in <module>
  File "dealer_gui.py", line 33, in __init__
  File "dealer_gui.py", line 44, in setup_ui
  File "dealer_gui.py", line 53, in configure_ui_theme
  File "C:\Users\J00643~1\AppData\Local\Temp\_MEI245362\awthemes\__init__.py", line 42, in theme_use
    tksvg.load(self.master)
  File "tksvg\__init__.py", line 26, in load
_tkinter.TclError: couldn't read file "pkgIndex.tcl": no such file or directory
```

**Comment by undecV** [comment]
Could you try adding the arguments `--collect-all "tksvg"` to see if it works properly?

Thank you for your response!

**Comment by Felix00643298** [comment]
> Could you try adding the arguments `--collect-all "tksvg"` to see if it works properly?
> 
> Thank you for your response!

It wokrs!
Thanks for responsing me. It is a great project.
